config/routes.rb
PowerMeMobileBlog::Application.routes.draw do

  get "sessions/new"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get '/admins/auth/:provider' => 'admins/omniauth_callbacks#passthru'
  end

  devise_for :admins, :controllers => { :sessions => "admins/sessions", :passwords => "admins/passwords" }

  resources :articles do
    resources :comments
  end

  resources :links

  root :to => 'articles#index'

  match ':controller(/:action(/:id(.:format)))'
end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_commentable

  validates_presence_of :title, :content

  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings

  def tag_names=(names)
    self.tags = Tag.with_names names.split
  end

  def tag_names
    tags.map(&:name).join(' ')
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource

  def index
    conditions = ['content like ? or title like ?', "%#{params[:s]}%", "%#{params[:s]}%"]
    if params[:tag_id]
      @articles = Tag.find(params[:tag_id]).articles.paginate(
          :per_page => 10,
          :page => params[:page],
          :conditions => conditions,
          :order => 'created_at DESC'
      )
    else
      @articles = Article.paginate(
        :include => :tags,
        :per_page => 10,
        :page => params[:page],
        :conditions => conditions,
        :order => 'created_at DESC'
      )
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :layout => false }
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.includes([{:comments => :user}, :tags]).find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :ok }
    end
  end
end

app/views/articles/_form.html.erb
<%= javascript_include_tag "../javascripts/ckeditor/ckeditor.js" %>
<div id="maincontent">
  <div id="content">
    <div class="postwrap fix">
      <div class="post-14 post type-post status-publish format-standard hentry category-uncategorized tag-wordpress">
        <div class="copy fix">
          <%= form_for(@article) do |f| %>
              <% if @article.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
                    <ul>
                      <% @article.errors.full_messages.each do |msg| %>
                          <li><%= msg %></li>
                      <% end %>
                    </ul>
                  </div>
              <% end %>
              <div class="field">
                <%= f.label :title %><br />
                <%= f.text_field :title, :size => "93%" %>
              </div>
              <div class="field">
                <%= f.label :content %><br />
                <%= f.cktext_area :content %>
              </div>
              <div class="field">
                <%= f.hidden_field :tag_names %>
              </div>
              <div style="height: 10px"></div>
              <div class="actions">
                <%= f.submit %>
              </div>
          <% end %>
        </div>
      </div>
      <div style="height: 10px"></div>
    </div>
    <div class="clear"></div>
  </div>
</div>
<div id="sidebar">
  <div id="dtags" class="widget_tag widget">
    <div class="winner">
      <h3 class="wtitle">Tags for this article</h3>
      <%= render "tags/index" %>
    </div>
  </div>
</div>

app/views/articles/_tagged_with.html.erb
<div class="tags">
  <% unless tags.empty? %>
      Tagged with
      <% first = true %>
      <% tags.each do |tag| %>
          <%= if first then ": " else " • " end %>
          <% first = false %>
          <%= link_to tag.name.capitalize, articles_path(tag_id: tag) %>
      <% end %>
  <% end %>
</div>

app/views/articles/edit.html.erb
<%= render 'form' %>
<div class="post_nav">
    <%= link_to 'Show', @article %> |
    <%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<div id="maincontent">
  <div id="content">
    <% @articles.each do |article| %>
        <div class="postwrap fix">
          <div class="post-14 post type-post status-publish format-standard hentry category-uncategorized tag-wordpress">
            <div class="copy fix">
              <div class="post-header fix post-nothumb">
                <div class="post-title-selection fix">
                  <div class="post-title fix">
                    <h2>
                      <%= link_to article.title, article %>
                    </h2>
                    <div class="metabar">
                      <em>
                        On <%= article.created_at %>
                      </em>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="copy fix">
              <div class="textcontent">
                <%= raw article.content %>
                <div class="clear"></div>
                <div class="clear"></div>
              </div>
            </div>
            <div class="hl"></div>
            <div class="post-footer">
              <div class="left">
                <span><%= article.comments.count %></span>
                <%= link_to "Comments", article_path(article) + "#comments" %>
              </div>
              <% if can?(:manage, article) %>
                  <div style="position: absolute; padding-left: 283px; padding-top: 15px;">
                    <%= link_to 'Edit', edit_article_path(article) %> |
                    <%= link_to 'Destroy', article, confirm: 'Are you sure?', method: :delete %>
                  </div>
              <% end %>
              <div class="right">
                <span>
                  <%= link_to "Leave A Response", article_path(article) + "#respond" %>
                </span>
              </div>
              <br class="fix">
            </div>
          </div>
        </div>
        <%= render "tagged_with", :tags => article.tags %>
        <div class="clear"></div>
    <% end %>
    <div class="post_nav">
      <%= will_paginate @articles, :inner_window => 1, :outer_window => 2 %>
    </div>
  </div>
</div>
<div id="sidebar">
  <div id="dtags" class="widget_tag widget">
    <div class="winner">
      <h3 class="wtitle">Tags</h3>
      <% Tag.all(:limit => 100).each do |tag| %>
          <%= link_to tag.name, articles_path(:tag_id => tag), :style => "color: #0088CC;" %>
      <% end %>
    </div>
  </div>
  <% if can? :read, Link %>
    <div id="dlinks" class="widget_links widget">
        <div class="winner">
          <h3 class="wtitle">Links</h3>
          <%= render 'shared/external_links' %>
        </div>
    </div>
  <% end %>
  <div id="dmeta" class="widget_meta widget">
    <div class="winner">
      <h3 class="wtitle">Meta</h3>
      <ul>
        <li>
          <%= render "admins/shared/session_links" %>
        </li>
        <li>
          <%= link_to "Entries RSS", articles_path + ".xml" %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<%= render 'form' %>

<div class="post_nav">
    <%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div class="postwrap fix">
  <div class="post-25 page type-page status-publish hentry">
    <div class="copy fix">
      <div class="pagetittle">
        <h2><%= @article.title %></h2>
      </div>
      <div class="pagecontent">
        <%= raw @article.content %>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</div>
<div class="clear"></div>

<%= render 'tagged_with', :tags => @article.tags %>

<%= render "comments/index" %>

<div class="post_nav">
  <% if can? :manage, @article %>
    <%= link_to 'Edit Article', edit_article_path(@article) %> |
    <%= link_to 'Destroy Article', @article, confirm: 'Are you sure?', method: :delete %> |
  <% end %>
  <%= link_to 'Back', articles_path %>
</div>