config/routes.rb
PowerMeMobileBlog::Application.routes.draw do

  get "sessions/new"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get '/admins/auth/:provider' => 'admins/omniauth_callbacks#passthru'
  end

  devise_for :admins, :controllers => { :sessions => "admins/sessions", :passwords => "admins/passwords" }

  resources :articles do
    resources :comments
  end

  resources :links

  root :to => 'articles#index'

  match ':controller(/:action(/:id(.:format)))'
end

app/views/shared/_external_links.html.erb
<ul>
  <% Link.all.each do |link| %>
      <li>
        <%= link_to link.title, link.url %>
        <% if can? :delete, link %>
            <%= link_to "x", link, :method => :delete, :confirm => "Are you sure?" %>
        <% end %>
      </li>
  <% end %>
  <% if can? :create, Link %>
      <b><%= link_to "New Link", new_link_path %></b>
  <% end %>
</ul>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="effect">
    <div class="content">
      <div id="fcolumns_container" class="fix">
        <div class="fcol">
          <div class="fcol_pad">
            <h3 class="footer-site-title">
              <%= link_to "Ruby on Rails Blog", root_url %>
            </h3>
          </div>
        </div>
        <div class="fcol">
          <div class="fcol_pad">
            <h3 class="links_title">Administration</h3>
            <ul>
              <li><%= render "admins/shared/session_links" %></li>
              <% if admin_signed_in? %>
                <li><%= link_to "New article", new_article_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="fcol">
          <div class="fcol_pad">
            <h3>Social networks login</h3>
            <div class="social_at_footer">
              <%= render "shared/social_login_buttons" %>
            </div>
          </div>
        </div>
        <div class="fcol">
          <div class="fcol_pad">
            <h3 class="links_title">
              Links
            </h3>
            <%= render "shared/external_links" %>
          </div>
        </div>
        <div class="fcol">
          <div class="fcol_pad">
            <span class="terms">
              © 2011 RoR test project
            </span>
          </div>
        </div>
      </div>
      <div class="clear"></div>
    </div>
  </div>
</div>
<div class="clear"></div>

app/views/shared/_nav.html.erb
<ul id="menu-main" class="mnav dropdown fix">
  <% if can? :create, Article %>
      <li>
        <%= link_to "New article", new_article_path %>
      </li>
  <% end %>
  <% unless user_signed_in? %>
      <li class="menu-item menu-item-type-post_type menu-item-object-page">
        <%= link_to "Login", new_admin_session_path %>
        <ul class="sub-menu">
          <li class="menu-item menu-item-type-post_type menu-item-object-page;">
            <%= link_to "Facebook",  user_omniauth_authorize_path(:facebook) %>
          </li>
          <li class="menu-item menu-item-type-post_type menu-item-object-page;">
            <%= link_to "Twitter",  user_omniauth_authorize_path(:twitter) %>
          </li>
        </ul>
      </li>
  <% end %>
  <% if user_signed_in? or admin_signed_in? %>
      <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
  <% end %>
</ul>
<%= form_tag({ :controller => :articles, :action => :index }, :class => "searchform", :method => :get) do %>
    <span class="left"></span>
    <%= text_field_tag :s,
                       "Search",
                       :class => "s",
                       :onfocus => "if (this.value == 'Search') {this.value = '';}",
                       :onblur => "if (this.value == '') {this.value = 'Search';}"
    %>
    <span class="right"></span>
    <%= submit_tag "Go", :class => "searchsubmit" %>
<% end %>

app/views/shared/_social_login_buttons.erb
<% if user_signed_in? %>
    <div class="nav-icon">
      Welcome <%= link_to current_user.name, current_user.link %>.
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
    </div>
<% else %>
    <div class="nav-icon">
      <%= link_to(image_tag("facebook.png"), user_omniauth_authorize_path(:facebook)) %>
    </div>
    <div class="nav-icon">
      <%= link_to(image_tag("twitter.png"), user_omniauth_authorize_path(:twitter)) %>
    </div>
<% end %>